from __future__ import annotations

import argparse
import ast
from collections.abc import Callable, Iterable
from dataclasses import dataclass
import difflib
from pathlib import Path
import re
import sys


sys.dont_write_bytecode = True

ROOT = Path(__file__).resolve().parents[2]

BEGIN_TEMPLATE = "<!-- BEGIN GENERATED: {block_id} -->"
END_TEMPLATE = "<!-- END GENERATED: {block_id} -->"


@dataclass(frozen=True)
class GeneratedBlock:
    path: Path
    block_id: str
    render: Callable[[], str]


def _add_workspace_paths() -> None:
    candidates = [ROOT, ROOT / "examples" / "equivalence_contracts" / "src"]
    for base in (ROOT / "pkgs" / "core", ROOT / "pkgs" / "apps", ROOT / "pkgs" / "engines"):
        if not base.is_dir():
            continue
        for child in sorted(base.iterdir()):
            if not child.is_dir():
                continue
            candidates.append(child)
            src = child / "src"
            if src.is_dir():
                candidates.append(src)

    for path in reversed(candidates):
        text = str(path)
        if text not in sys.path:
            sys.path.insert(0, text)


def _code(value: str) -> str:
    return f"`{value}`"


def _code_list(values: Iterable[str], *, none: str = "none") -> str:
    items = [str(value) for value in values]
    if not items:
        return none
    return ", ".join(_code(item) for item in items)


def _markdown_table(headers: list[str], rows: list[list[str]]) -> str:
    out = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    out.extend("| " + " | ".join(row) + " |" for row in rows)
    return "\n".join(out)


def _generated_note(sources: Iterable[str]) -> str:
    source_text = ", ".join(_code(source) for source in sources)
    return (
        "Generated by `tools/docs/update_equivalence_docs.py`. "
        "Edit the source inputs, then run "
        "`python tools/docs/update_equivalence_docs.py --write`.\n\n"
        f"Source inputs: {source_text}."
    )


def _format_status(missing: list[str]) -> str:
    if not missing:
        return "present"
    return "missing: " + _code_list(missing)


def _facade_exports() -> set[str]:
    facade = ROOT / "pkgs" / "core" / "tigrbl" / "tigrbl" / "__init__.py"
    tree = ast.parse(facade.read_text(encoding="utf-8"))
    exports: set[str] = set()
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if not any(isinstance(target, ast.Name) and target.id == "__all__" for target in node.targets):
            continue
        if not isinstance(node.value, (ast.List, ast.Tuple)):
            continue
        for item in node.value.elts:
            if isinstance(item, ast.Constant) and isinstance(item.value, str):
                exports.add(item.value)
    return exports


def _public_surface_rows(groups: list[tuple[str, list[str]]]) -> list[list[str]]:
    exported = _facade_exports()
    rows: list[list[str]] = []
    for label, symbols in groups:
        missing = [symbol for symbol in symbols if symbol not in exported]
        rows.append([label, _code_list(symbols), _format_status(missing)])
    return rows


def render_authoring_public_surface() -> str:
    groups = [
        (
            "App and router authoring",
            ["TigrblApp", "TigrblRouter", "AppSpec", "RouterSpec", "include_table", "include_tables"],
        ),
        (
            "Table and resource authoring",
            ["Table", "TableBase", "CrudTable", "RestTable", "JsonRpcTable", "RestJsonRpcTable"],
        ),
        (
            "Operation and binding authoring",
            [
                "OpSpec",
                "HTTPBindingSpec",
                "HttpRestBindingSpec",
                "HttpJsonRpcBindingSpec",
                "HttpStreamBindingSpec",
                "SseBindingSpec",
                "WebSocketBindingSpec",
                "WsBindingSpec",
                "WebTransportBindingSpec",
            ],
        ),
        (
            "Schema, column, and response authoring",
            ["ColumnSpec", "FieldSpec", "IOSpec", "StorageSpec", "SchemaSpec", "ResponseSpec"],
        ),
        (
            "Engine, session, and hook authoring",
            ["EngineSpec", "engine_ctx", "session_spec", "op_ctx", "hook_ctx", "response_ctx"],
        ),
    ]
    return "\n\n".join(
        [
            _generated_note(
                [
                    "pkgs/core/tigrbl/tigrbl/__init__.py",
                    "pkgs/core/tigrbl_core/tigrbl_core/_spec/",
                ]
            ),
            _markdown_table(
                ["Surface group", "Required public symbols", "Export status"],
                _public_surface_rows(groups),
            ),
        ]
    )


def render_router_table_public_surface() -> str:
    groups = [
        (
            "Router composition",
            ["TigrblRouter", "RouterSpec", "include_table", "include_tables"],
        ),
        (
            "Table bases and specs",
            ["Table", "TableBase", "CrudTableBase", "RealtimeTableBase", "TableSpec", "TableProfileSpec"],
        ),
        (
            "REST and JSON-RPC table classes",
            [
                "CrudTable",
                "RestTable",
                "JsonRpcTable",
                "RestJsonRpcTable",
                "RestBulkCrudTable",
                "JsonRpcBulkCrudTable",
            ],
        ),
        (
            "OLTP and OLAP table classes",
            ["OltpTable", "RestOltpTable", "JsonRpcOltpTable", "OlapTable", "RestOlapTable", "JsonRpcOlapTable"],
        ),
        (
            "Streaming table classes",
            ["StreamTable", "SseTable", "EventStreamTable", "WebSocketTable", "WebSocketJsonRpcTable"],
        ),
        (
            "WebTransport table classes",
            [
                "WebTransportTable",
                "WebTransportBidiTable",
                "WebTransportClientStreamTable",
                "WebTransportServerStreamTable",
                "WebTransportDatagramTable",
            ],
        ),
    ]
    return "\n\n".join(
        [
            _generated_note(
                [
                    "pkgs/core/tigrbl/tigrbl/__init__.py",
                    "pkgs/core/tigrbl_core/tigrbl_core/_spec/table_profile_spec.py",
                ]
            ),
            _markdown_table(
                ["Surface group", "Required public symbols", "Export status"],
                _public_surface_rows(groups),
            ),
        ]
    )


def render_table_profile_snapshot() -> str:
    _add_workspace_paths()
    from tigrbl_core._spec.table_profile_spec import (  # noqa: PLC0415
        iter_builtin_table_profile_definitions,
    )

    rows = []
    for row in iter_builtin_table_profile_definitions():
        rows.append(
            [
                _code(row.kind),
                _code(row.role),
                _code_list(row.targets),
                _code_list(row.binding_families),
                _code(row.docs_exposure),
                _code(row.runtime_exposure),
                _code_list(row.public_class_names),
            ]
        )
    return "\n\n".join(
        [
            _generated_note(
                ["pkgs/core/tigrbl_core/tigrbl_core/_spec/table_profile_spec.py"]
            ),
            _markdown_table(
                [
                    "Profile kind",
                    "Role",
                    "Targets",
                    "Binding families",
                    "Docs exposure",
                    "Runtime exposure",
                    "Public classes",
                ],
                rows,
            ),
        ]
    )


def _transport_order(keys: Iterable[str]) -> list[str]:
    preferred = [
        "http.rest",
        "https.rest",
        "http.jsonrpc",
        "https.jsonrpc",
        "http.stream",
        "https.stream",
        "http.sse",
        "https.sse",
        "ws",
        "wss",
        "webtransport",
    ]
    key_set = set(keys)
    return [key for key in preferred if key in key_set] + sorted(key_set - set(preferred))


def render_transport_binding_support() -> str:
    _add_workspace_paths()
    from tigrbl_core._spec.binding_spec import (  # noqa: PLC0415
        APP_LEVEL_FRAMING_SUPPORT,
        BINDING_PROFILE_EXCHANGE_SUPPORT,
    )

    rows = []
    for binding_kind in _transport_order(APP_LEVEL_FRAMING_SUPPORT):
        rows.append(
            [
                _code(binding_kind),
                _code_list(APP_LEVEL_FRAMING_SUPPORT[binding_kind]),
                _code_list(BINDING_PROFILE_EXCHANGE_SUPPORT.get(binding_kind, ())),
            ]
        )
    return "\n\n".join(
        [
            _generated_note(
                ["pkgs/core/tigrbl_core/tigrbl_core/_spec/binding_spec.py"]
            ),
            _markdown_table(
                ["Binding kind", "Allowed app-level framing", "Allowed exchanges"],
                rows,
            ),
        ]
    )


def render_webtransport_lane_support() -> str:
    _add_workspace_paths()
    from tigrbl_core._spec.binding_spec import (  # noqa: PLC0415
        WEBTRANSPORT_INNER_FRAMING_SUPPORT,
        WEBTRANSPORT_LANE_EXCHANGES,
        WEBTRANSPORT_NATIVE_LANES,
        webtransport_runtime_family,
    )

    rows = []
    for lane in WEBTRANSPORT_NATIVE_LANES:
        rows.append(
            [
                _code(lane),
                _code(webtransport_runtime_family(lane)),
                _code_list(WEBTRANSPORT_INNER_FRAMING_SUPPORT[lane]),
                _code(WEBTRANSPORT_LANE_EXCHANGES[lane]),
            ]
        )
    return "\n\n".join(
        [
            _generated_note(
                ["pkgs/core/tigrbl_core/tigrbl_core/_spec/binding_spec.py"]
            ),
            _markdown_table(
                ["Lane", "Runtime family", "Allowed inner framing", "Required exchange"],
                rows,
            ),
        ]
    )


def _parse_engine_entry_points(pyproject: Path) -> list[str]:
    text = pyproject.read_text(encoding="utf-8")
    section = re.search(
        r'(?ms)^\[project\.entry-points\."tigrbl\.engine"\]\s*(.*?)(?=^\[|\Z)',
        text,
    )
    if section is None:
        return []
    entries: list[str] = []
    for line in section.group(1).splitlines():
        match = re.match(r"\s*([A-Za-z0-9_.-]+)\s*=\s*\"[^\"]+\"", line)
        if match:
            entries.append(match.group(1))
    return sorted(entries)


def _parse_project_name(pyproject: Path) -> str:
    text = pyproject.read_text(encoding="utf-8")
    match = re.search(r'(?m)^name\s*=\s*"([^"]+)"', text)
    return match.group(1) if match else pyproject.parent.name


def render_engine_package_snapshot() -> str:
    rows = []
    for pyproject in sorted((ROOT / "pkgs" / "engines").glob("*/pyproject.toml")):
        package_name = _parse_project_name(pyproject)
        rows.append(
            [
                _code(package_name),
                _code_list(_parse_engine_entry_points(pyproject)),
                _code(package_name),
                _code(pyproject.parent.relative_to(ROOT).as_posix()),
            ]
        )
    return "\n\n".join(
        [
            _generated_note(["pkgs/engines/*/pyproject.toml"]),
            _markdown_table(
                ["Package", "Engine entry points", "Import root", "Repository path"],
                rows,
            ),
        ]
    )


def _engine_order(engines: Iterable[str]) -> list[str]:
    preferred = ["sqlite", "postgres", "dataframe", "file", "cache"]
    engine_set = set(engines)
    return [engine for engine in preferred if engine in engine_set] + sorted(
        engine_set - set(preferred)
    )


def render_datatype_lowering_matrix() -> str:
    _add_workspace_paths()
    from tigrbl_core._spec.datatypes import (  # noqa: PLC0415
        CANONICAL_DATATYPES,
        DataTypeSpec,
        EngineDatatypeBridge,
        EngineRegistry,
    )

    registry = EngineRegistry()
    bridge = EngineDatatypeBridge(registry)
    engines = _engine_order(registry.known_engines())
    rows = []
    for logical_name in CANONICAL_DATATYPES:
        row = [_code(logical_name)]
        for engine in engines:
            try:
                lowered = bridge.lower(engine, DataTypeSpec(logical_name), strict=True)
                row.append(_code(lowered.physical_name))
            except LookupError:
                row.append("not mapped")
        rows.append(row)

    headers = ["Logical datatype"] + [engine.title() for engine in engines]
    return "\n\n".join(
        [
            _generated_note(
                ["pkgs/core/tigrbl_core/tigrbl_core/_spec/datatypes.py"]
            ),
            _markdown_table(headers, rows),
        ]
    )


def render_reflection_hints() -> str:
    _add_workspace_paths()
    from tigrbl_core._spec import datatypes as datatype_mod  # noqa: PLC0415

    hints = getattr(datatype_mod, "_REFLECTION_HINTS")
    rows = []
    for engine_key in [None, "sqlite", "postgres"]:
        mapping = hints.get(engine_key, {})
        by_logical: dict[str, list[str]] = {}
        for physical_name, logical_hint in sorted(mapping.items()):
            by_logical.setdefault(logical_hint, []).append(physical_name)
        label = "generic" if engine_key is None else str(engine_key)
        for logical_hint in sorted(by_logical):
            rows.append(
                [
                    _code(label),
                    _code_list(by_logical[logical_hint]),
                    _code(logical_hint),
                ]
            )

    return "\n\n".join(
        [
            _generated_note(
                ["pkgs/core/tigrbl_core/tigrbl_core/_spec/datatypes.py"]
            ),
            _markdown_table(["Engine family", "Physical names", "Logical hint"], rows),
        ]
    )


def render_certifiable_equivalence_matrix() -> str:
    _add_workspace_paths()
    from tigrbl_equivalence_contracts import matrix_rows  # noqa: PLC0415

    rows = []
    for row in matrix_rows():
        rows.append(
            [
                _code(row["id"]),
                row["category"],
                row["intent"],
                _code(row["status"]),
                _code(row["tigrbl"]),
                _code(row["fastapi"]),
                _code(row["flask"]),
                _code(row["test"]),
            ]
        )
    return "\n\n".join(
        [
            _generated_note(
                [
                    "examples/equivalence_contracts/src/tigrbl_equivalence_contracts/contracts.py",
                    "examples/equivalence_contracts/src/tigrbl_equivalence_contracts/equivalences/",
                    "examples/equivalence_contracts/tests/test_certifiable_equivalences.py",
                ]
            ),
            _markdown_table(
                [
                    "Equivalence ID",
                    "Category",
                    "Intent",
                    "Status",
                    "Tigrbl code",
                    "FastAPI code",
                    "Flask code",
                    "Parity test",
                ],
                rows,
            ),
        ]
    )


def generated_blocks() -> tuple[GeneratedBlock, ...]:
    return (
        GeneratedBlock(
            ROOT / "docs" / "developer" / "AUTHORING_EQUIVALENCE.md",
            "equivalence-docs:authoring-public-surface",
            render_authoring_public_surface,
        ),
        GeneratedBlock(
            ROOT / "docs" / "developer" / "ROUTER_TABLE_EQUIVALENCE.md",
            "equivalence-docs:router-table-public-surface",
            render_router_table_public_surface,
        ),
        GeneratedBlock(
            ROOT / "docs" / "developer" / "ROUTER_TABLE_EQUIVALENCE.md",
            "equivalence-docs:table-profiles",
            render_table_profile_snapshot,
        ),
        GeneratedBlock(
            ROOT / "docs" / "developer" / "TRANSPORT_EQUIVALENCE.md",
            "equivalence-docs:transport-binding-support",
            render_transport_binding_support,
        ),
        GeneratedBlock(
            ROOT / "docs" / "developer" / "TRANSPORT_EQUIVALENCE.md",
            "equivalence-docs:webtransport-lane-support",
            render_webtransport_lane_support,
        ),
        GeneratedBlock(
            ROOT / "docs" / "developer" / "ENGINE_SQL_EQUIVALENCE.md",
            "equivalence-docs:engine-packages",
            render_engine_package_snapshot,
        ),
        GeneratedBlock(
            ROOT / "docs" / "developer" / "ENGINE_SQL_EQUIVALENCE.md",
            "equivalence-docs:datatype-lowering",
            render_datatype_lowering_matrix,
        ),
        GeneratedBlock(
            ROOT / "docs" / "developer" / "ENGINE_SQL_EQUIVALENCE.md",
            "equivalence-docs:reflection-hints",
            render_reflection_hints,
        ),
        GeneratedBlock(
            ROOT / "docs" / "developer" / "EQUIVALENCE_INDEX.md",
            "equivalence-docs:certifiable-matrix",
            render_certifiable_equivalence_matrix,
        ),
    )


def _wrap_block(block_id: str, body: str) -> str:
    return (
        f"{BEGIN_TEMPLATE.format(block_id=block_id)}\n"
        f"{body.rstrip()}\n"
        f"{END_TEMPLATE.format(block_id=block_id)}"
    )


def _replace_block(text: str, block_id: str, replacement: str) -> tuple[str, bool]:
    begin = BEGIN_TEMPLATE.format(block_id=block_id)
    end = END_TEMPLATE.format(block_id=block_id)
    pattern = re.compile(
        re.escape(begin) + r".*?" + re.escape(end),
        re.DOTALL,
    )
    new_text, count = pattern.subn(replacement, text, count=1)
    return new_text, count == 1


def _expected_text(path: Path, blocks: list[GeneratedBlock]) -> tuple[str | None, list[str]]:
    errors: list[str] = []
    text = path.read_text(encoding="utf-8")
    updated = text
    for block in blocks:
        replacement = _wrap_block(block.block_id, block.render())
        updated, found = _replace_block(updated, block.block_id, replacement)
        if not found:
            errors.append(
                f"{path.relative_to(ROOT).as_posix()} missing generated block {block.block_id}"
            )
    if errors:
        return None, errors
    return updated, []


def check_docs() -> list[str]:
    errors: list[str] = []
    blocks_by_path: dict[Path, list[GeneratedBlock]] = {}
    for block in generated_blocks():
        blocks_by_path.setdefault(block.path, []).append(block)

    for path, blocks in sorted(blocks_by_path.items()):
        expected, path_errors = _expected_text(path, blocks)
        errors.extend(path_errors)
        if expected is None:
            continue
        current = path.read_text(encoding="utf-8")
        if current != expected:
            diff = "\n".join(
                difflib.unified_diff(
                    current.splitlines(),
                    expected.splitlines(),
                    fromfile=f"{path.relative_to(ROOT).as_posix()} (current)",
                    tofile=f"{path.relative_to(ROOT).as_posix()} (generated)",
                    lineterm="",
                    n=3,
                )
            )
            errors.append(
                f"{path.relative_to(ROOT).as_posix()} generated equivalence block is stale.\n{diff}"
            )
    return errors


def write_docs() -> list[str]:
    errors: list[str] = []
    changed: list[str] = []
    blocks_by_path: dict[Path, list[GeneratedBlock]] = {}
    for block in generated_blocks():
        blocks_by_path.setdefault(block.path, []).append(block)

    for path, blocks in sorted(blocks_by_path.items()):
        expected, path_errors = _expected_text(path, blocks)
        errors.extend(path_errors)
        if expected is None:
            continue
        current = path.read_text(encoding="utf-8")
        if current != expected:
            path.write_text(expected, encoding="utf-8")
            changed.append(path.relative_to(ROOT).as_posix())

    if changed:
        print("Updated generated equivalence docs:")
        for item in changed:
            print(f"- {item}")
    else:
        print("Generated equivalence docs are current.")
    return errors


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Update or verify generated sections in equivalence docs."
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="Fail if generated blocks are stale.")
    mode.add_argument("--write", action="store_true", help="Rewrite generated blocks in place.")
    args = parser.parse_args()

    errors = write_docs() if args.write else check_docs()
    if errors:
        for error in errors:
            print(error, file=sys.stderr)
        raise SystemExit(1)
    if args.check:
        print("generated equivalence docs validation passed")


if __name__ == "__main__":
    main()
